// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWiVL31xUZ3RuZckrAnjO4W4SI3sQ2jM',
    appId: '1:930516571839:web:f87d8758ff8ca4c214580a',
    messagingSenderId: '930516571839',
    projectId: 'elms-b657e',
    authDomain: 'elms-b657e.firebaseapp.com',
    storageBucket: 'elms-b657e.appspot.com',
    measurementId: 'G-DHXVC3K0YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8f1JiRimQfDTzw1BBnORMRiDlVJKrTNI',
    appId: '1:930516571839:android:6f35b21be7c4022914580a',
    messagingSenderId: '930516571839',
    projectId: 'elms-b657e',
    storageBucket: 'elms-b657e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBssfwAwbPUz91k63prGnWMGql5DKbBhU',
    appId: '1:930516571839:ios:cdeab513f4af590014580a',
    messagingSenderId: '930516571839',
    projectId: 'elms-b657e',
    storageBucket: 'elms-b657e.appspot.com',
    iosBundleId: 'com.example.elms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBssfwAwbPUz91k63prGnWMGql5DKbBhU',
    appId: '1:930516571839:ios:cdeab513f4af590014580a',
    messagingSenderId: '930516571839',
    projectId: 'elms-b657e',
    storageBucket: 'elms-b657e.appspot.com',
    iosBundleId: 'com.example.elms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxWiVL31xUZ3RuZckrAnjO4W4SI3sQ2jM',
    appId: '1:930516571839:web:e27ff6c666781b9414580a',
    messagingSenderId: '930516571839',
    projectId: 'elms-b657e',
    authDomain: 'elms-b657e.firebaseapp.com',
    storageBucket: 'elms-b657e.appspot.com',
    measurementId: 'G-SLZJGX13NB',
  );
}
